import type { Metadata } from "next";
import { Inter, Jaldi } from "next/font/google";
import "../globals.css";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import Navbar from "./Navbar";
import AuthProvider from "@/context/AuthProvider";
import Footer from "./Footer";

const jaldi = Jaldi({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jaldi.className}>
        <AuthProvider>
          <Theme>
            <Navbar />
            <main>
              {children}
            </main>
            <Footer />
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
